routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::get('setlocale/{locale}',function($lang){
    \Session::put('locale', $lang);
    return redirect()->back();
})->name('setlocale');


Route::middleware('language')->group(function () {
    Route::get('/', 'HomeController@home')->name('home');
    Route::get('/private-tours', 'HomeController@privateTours')->name('private.tours');
    Route::get('/everyday-taxi', 'HomeController@everydayTaxi')->name('everyday.taxi');
    Route::get('/airport-transport', 'HomeController@airportTransport')->name('airport.transport');
    Route::get('/cruise-transport', 'HomeController@cruiseTransport')->name('cruise.transport');
    Route::get('/faq', 'HomeController@faq')->name('faq');
    Route::get('/contact', 'HomeController@contact')->name('contact');
    Route::get('/get-a-quote', 'HomeController@getAQuote')->name('get.quote');
    Route::post('/book', 'HomeController@booking')->name('book');
    Route::get('/thankyou', 'HomeController@thankYou')->name('thankyou');
    Route::get('/payment', 'HomeController@payment')->name('payment');
    Route::post('/payment-save', 'HomeController@paymentSave')->name('payment.save');
    Route::post('/contact-save', 'HomeController@contactSave')->name('contact.save');
});


// Admin Unathenticated Routes
Route::get('admin/login', 'Auth\AuthenticatedSessionController@showAdminLoginForm')->name('admin.login');

Route::prefix('admin')->name('admin.')->namespace('Admin')->middleware('auth', 'admin')->group(function() {
    Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
    Route::get('profile', 'DashboardController@profile')->name('profile');
    Route::get('enquiries', 'DashboardController@enquiries')->name('enquiries');
    Route::post('general-update', 'DashboardController@generalUpdate')->name('general.update');
    Route::post('pass-update', 'DashboardController@passUpdate')->name('pass.update');
    Route::get('settings', 'SettingController@settings')->name('setting');
    Route::post('setting-save', 'SettingController@save')->name('setting.save');

    Route::get('transaction', 'DashboardController@transaction')->name('transaction');

    Route::prefix('terminal')->name('terminal.')->group(function() {
    	Route::get('list', 'TerminalController@list')->name('list');
    	Route::get('add', 'TerminalController@add')->name('add');
    	Route::post('save/{id?}', 'TerminalController@save')->name('save');
    	Route::get('edit/{id?}', 'TerminalController@edit')->name('edit');
    	Route::get('delete/{id?}', 'TerminalController@delete')->name('delete');

        Route::get('bulk-action', 'TerminalController@bulkAction')->name('bulk.action');
	});

    Route::prefix('faq')->name('faq.')->group(function() {
    	Route::get('list', 'FaqController@list')->name('list');
    	Route::get('add', 'FaqController@add')->name('add');
    	Route::post('save/{id?}', 'FaqController@save')->name('save');
    	Route::get('edit/{id?}', 'FaqController@edit')->name('edit');
    	Route::get('delete/{id?}', 'FaqController@delete')->name('delete');

    	Route::get('status-change/{id?}', 'FaqController@statusChange')->name('status.change');
        Route::get('bulk-action', 'FaqController@bulkAction')->name('bulk.action');
	});

    Route::prefix('booking')->name('booking.')->group(function() {
    	Route::get('list/{status?}', 'BookingController@list')->name('list');
        Route::get('detail/{id?}', 'BookingController@detail')->name('detail');

        Route::get('status-change/{id?}/{action?}', 'BookingController@statusChange')->name('status.change');
    });

    Route::prefix('cms')->name('cms.')->group(function() {
        Route::get('home-page', 'SettingController@homePage')->name('home.page');
        Route::get('private-tours', 'SettingController@privateTours')->name('private.tours');
        Route::get('everyday-taxi', 'SettingController@everydayTaxi')->name('everyday.taxi');
        Route::get('airport-transport', 'SettingController@airportTransport')->name('airport.transport');
        Route::get('cruise-transport', 'SettingController@cruiseTransport')->name('cruise.transport');
    });
});

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')
@section('title', 'Dashboard')
@section('nav-title', 'Dashboard')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <a href="{{ route('admin.terminal.list') }}">
                <div class="card card-stats">
                    <div class="card-header card-header-warning card-header-icon">
                        <div class="card-icon"><i class="material-icons">category</i></div>
                        <p class="card-category">Terminals</p>
                        <h3 class="card-title">{{ $terminalCount }}</h3>
                    </div>
                    <div class="card-footer">
                        <div class="stats"><i class="material-icons">category</i> Total # of terminals</div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
            <a href="{{ route('admin.booking.list', 'completed') }}">
                <div class="card card-stats">
                    <div class="card-header card-header-success card-header-icon">
                        <div class="card-icon"><i class="material-icons">fact_check</i></div>
                        <p class="card-category">All Bookings</p>
                        <h3 class="card-title">{{ $completedBooking }}</h3>
                    </div>
                    <div class="card-footer">
                        <div class="stats"><i class="material-icons">fact_check</i> Total # of bookings</div>
                    </div>
                </div>
            </a>
        </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/enquiries.blade.php
@extends('layouts.admin')
@section('title', 'Contact Enquries')
@section('nav-title', 'Contact Enquries')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon"><i class="material-icons">list</i></div>
                </div>
                <div class="card-body">
                	<div class="material-datatables mt-3">
                        <table class="datatables table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Date</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Message</th>
                                </tr>
                            </thead>
                            <tbody>
                            	@foreach ($enq as $item)
                                <tr>
                                	<td>{{ $item->id }}</td>
                                	<td>{{ $item->created_at->format('d/m/Y') }}</td>
                                	<td>{{ $item->name }}</td>
                                	<td>{{ $item->email }}</td>
                                	<td>{{ $item->message }}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/profile.blade.php
@extends('layouts.admin')
@section('title', 'Edit Profile')
@section('nav-title', 'Edit Profile')
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="page-categories">
                    <ul class="nav nav-pills nav-pills-rose nav-pills-icons" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" id="general-tab" href="#general" role="tablist">
                                <i class="material-icons">info</i> General Info
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" id="security-tab" href="#security" role="tablist">
                                <i class="material-icons">lock</i> Security
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content tab-space tab-subcategories">
                        <div class="tab-pane active" id="general">
                            <div class="card">
                                <div class="card-body">
                                    <form action="{{ route('admin.general.update') }}" method="POST">
                                        @csrf
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating">Name</label>
                                                    <input type="text" name="name" value="{{ $user->name }}" class="form-control @error('name') is-invalid @enderror" autocomplete="off">
                                                    @error('name')
                                                        <span class="invalid-feedback">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating">Email</label>
                                                    <input type="email" name="email" value="{{ $user->email }}" class="form-control @error('email') is-invalid @enderror" autocomplete="off">
                                                    @error('email')
                                                        <span class="invalid-feedback">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-rose pull-right">Update</button>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="security">
                            <div class="card">
                                <div class="card-body">
                                    <form action="{{ route('admin.pass.update') }}" method="POST">
                                        @csrf
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating">Current Password</label>
                                                    <input type="password" name="current_password" class="form-control @error('current_password') is-invalid @enderror" autocomplete="off">
                                                    @error('current_password')
                                                        <span class="invalid-feedback">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating">New Password</label>
                                                    <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" autocomplete="off">
                                                    @error('password')
                                                        <span class="invalid-feedback">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="bmd-label-floating">Confirm Password</label>
                                                    <input type="password" name="password_confirmation" class="form-control @error('password_confirmation') is-invalid @enderror" autocomplete="off">
                                                    @error('password_confirmation')
                                                        <span class="invalid-feedback">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-rose pull-right">Update</button>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">

            </div>
        </div>
    </div>

@endsection
@section('js')
    <script>
        $gen_session = "{{ session('general_error') }}";
        $pass_session = "{{ session('pass_error') }}";

        if ($gen_session == 1) {
            $('.nav-link').removeClass('active');
            $('.tab-pane').removeClass('active');

            $("#general").addClass('active');
            $("#general-tab").addClass('active');
        } else if ($pass_session == 1) {
            $('.nav-link').removeClass('active');
            $('.tab-pane').removeClass('active');

            $("#security").addClass('active');
            $("#security-tab").addClass('active');
        }
    </script>
@endsection

resources/views/admin/setting.blade.php
@extends('layouts.admin')
@section('title', 'CMS')
@section('nav-title', 'CMS')
@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form action="{{ route('admin.setting.save') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card ">
                    <div class="card-header card-header-rose card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">settings</i>
                        </div>
                        <h5 class="card-title">Settings</h5>
                    </div>
                    <div class="card-body ">
                    	<div class="row">
                            <div class="col-md-12">
                    		    <h4 style="font-weight:bold;">Booking Panel On/Off</h4>
                    		</div>
                    		<div class="col-md-6">
                    			<div class="form-group">
                    				<label for="booking_panel_on_time">On Time</label>
                                    <input type="text" onkeydown="return false;" class="form-control timepicker" name="booking_panel_on_time" id="booking_panel_on_time" value="{{ setting('booking_panel_on_time') }}" autocomplete="off">
                    			</div>
                    		</div>
                            <div class="col-md-6">
                    			<div class="form-group">
                    				<label for="booking_panel_off_time">Off Time</label>
                                    <input type="text" onkeydown="return false;" class="form-control timepicker" name="booking_panel_off_time" id="booking_panel_off_time" value="{{ setting('booking_panel_off_time') }}" autocomplete="off">
                    			</div>
                    		</div>

                    	    <div class="col-md-12">
                                <hr>
                    		    <h4 style="font-weight:bold;">Bus(8 person) Prices</h4>
                    		</div>
                    		<div class="col-md-6">
                    			<div class="form-group">
                    				<label for="fare_rate">Per KM</label>
                                    <input type="text" class="form-control" name="bus_per_km" id="bus_per_km" value="{{ setting('bus_per_km') }}" autocomplete="off">
                    			</div>
                    		</div>
                            <div class="col-md-6">
                    			<div class="form-group">
                    				<label for="base_fare">Per Minute</label>
                                    <input type="text" class="form-control" name="bus_per_minute" id="bus_per_minute" value="{{ setting('bus_per_minute') }}" autocomplete="off">
                    			</div>
                    		</div>



                    		<div class="col-md-12">
                    		    <hr>
                    		    <h4 style="font-weight:bold;">Sedan and Stationwagen Prices</h4>
                    		</div>

                    		<div class="col-md-6">
                    			<div class="form-group">
                    				<label for="fare_rate">Per KM</label>
                                    <input type="text" class="form-control" name="sedan_per_km" id="sedan_per_km" value="{{ setting('sedan_per_km') }}" autocomplete="off">
                    			</div>
                    		</div>
                            <div class="col-md-6">
                    			<div class="form-group">
                    				<label for="base_fare">Per Minute</label>
                                    <input type="text" class="form-control" name="sedan_per_minute" id="sedan_per_minute" value="{{ setting('sedan_per_minute') }}" autocomplete="off">
                    			</div>
                    		</div>
                    		<div class="col-md-12">
                    		    <hr>
                    		</div>

                            <div class="col-md-6">
                    			<div class="form-group">
                    				<label for="miles_limit">Email addrees (Get order confirmation)</label>
                                    <input type="text" class="form-control" name="confirmation_email" id="confirmation_email" value="{{ setting('confirmation_email') }}" autocomplete="off">
                    			</div>
                    		</div>
                    		<div class="col-md-6">
                    			<div class="form-group">
                    				<label for="miles_limit">Secondary Email addrees (Get order confirmation)</label>
                                    <input type="text" class="form-control" name="secondary_confirmation_email" id="secondary_confirmation_email" value="{{ setting('secondary_confirmation_email') }}" autocomplete="off">
                    			</div>
                    		</div>
                    	</div>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-rose">Save Changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/transaction.blade.php
@extends('layouts.admin')
@section('title', 'Transactions')
@section('nav-title', 'Transactions')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon"><i class="material-icons">list</i></div>
                    <h5 class="card-title">
                        @if (isset($req->booking_id))
                            Booking ID: {{ $booking->uuid }} Transaction
                        @else
                            Transactions List
                        @endif
                    </h5>
                </div>
                <div class="card-body">
                	<div class="material-datatables mt-3">
                        <table class="datatables table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Date</th>
                                    <th>Stripe Charge ID</th>
                                    <th>Amount</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                            	@foreach ($list as $item)
                                <tr>
                                	<td>{{ $item->id }}</td>
                                	<td>{{ $item->created_at->format('d/m/Y') }}</td>
                                	<td>{{ $item->stripe_charge_id }}</td>
                                	<td>£{{ $item->amount }}</td>
                                    <td class="text-center">
                                        @if ($item->status == "1")
                                            <span class="badge badge-success">Captured</span>
                                        @else
                                            <span class="badge badge-danger">Refunded</span>
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection