routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::get('setlocale/{locale}',function($lang){
    \Session::put('locale', $lang);
    return redirect()->back();
})->name('setlocale');


Route::middleware('language')->group(function () {
    Route::get('/', 'HomeController@home')->name('home');
    Route::get('/private-tours', 'HomeController@privateTours')->name('private.tours');
    Route::get('/everyday-taxi', 'HomeController@everydayTaxi')->name('everyday.taxi');
    Route::get('/airport-transport', 'HomeController@airportTransport')->name('airport.transport');
    Route::get('/cruise-transport', 'HomeController@cruiseTransport')->name('cruise.transport');
    Route::get('/faq', 'HomeController@faq')->name('faq');
    Route::get('/contact', 'HomeController@contact')->name('contact');
    Route::get('/get-a-quote', 'HomeController@getAQuote')->name('get.quote');
    Route::post('/book', 'HomeController@booking')->name('book');
    Route::get('/thankyou', 'HomeController@thankYou')->name('thankyou');
    Route::get('/payment', 'HomeController@payment')->name('payment');
    Route::post('/payment-save', 'HomeController@paymentSave')->name('payment.save');
    Route::post('/contact-save', 'HomeController@contactSave')->name('contact.save');
});


// Admin Unathenticated Routes
Route::get('admin/login', 'Auth\AuthenticatedSessionController@showAdminLoginForm')->name('admin.login');

Route::prefix('admin')->name('admin.')->namespace('Admin')->middleware('auth', 'admin')->group(function() {
    Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
    Route::get('profile', 'DashboardController@profile')->name('profile');
    Route::get('enquiries', 'DashboardController@enquiries')->name('enquiries');
    Route::post('general-update', 'DashboardController@generalUpdate')->name('general.update');
    Route::post('pass-update', 'DashboardController@passUpdate')->name('pass.update');
    Route::get('settings', 'SettingController@settings')->name('setting');
    Route::post('setting-save', 'SettingController@save')->name('setting.save');

    Route::get('transaction', 'DashboardController@transaction')->name('transaction');

    Route::prefix('terminal')->name('terminal.')->group(function() {
    	Route::get('list', 'TerminalController@list')->name('list');
    	Route::get('add', 'TerminalController@add')->name('add');
    	Route::post('save/{id?}', 'TerminalController@save')->name('save');
    	Route::get('edit/{id?}', 'TerminalController@edit')->name('edit');
    	Route::get('delete/{id?}', 'TerminalController@delete')->name('delete');

        Route::get('bulk-action', 'TerminalController@bulkAction')->name('bulk.action');
	});

    Route::prefix('faq')->name('faq.')->group(function() {
    	Route::get('list', 'FaqController@list')->name('list');
    	Route::get('add', 'FaqController@add')->name('add');
    	Route::post('save/{id?}', 'FaqController@save')->name('save');
    	Route::get('edit/{id?}', 'FaqController@edit')->name('edit');
    	Route::get('delete/{id?}', 'FaqController@delete')->name('delete');

    	Route::get('status-change/{id?}', 'FaqController@statusChange')->name('status.change');
        Route::get('bulk-action', 'FaqController@bulkAction')->name('bulk.action');
	});

    Route::prefix('booking')->name('booking.')->group(function() {
    	Route::get('list/{status?}', 'BookingController@list')->name('list');
        Route::get('detail/{id?}', 'BookingController@detail')->name('detail');

        Route::get('status-change/{id?}/{action?}', 'BookingController@statusChange')->name('status.change');
    });

    Route::prefix('cms')->name('cms.')->group(function() {
        Route::get('home-page', 'SettingController@homePage')->name('home.page');
        Route::get('private-tours', 'SettingController@privateTours')->name('private.tours');
        Route::get('everyday-taxi', 'SettingController@everydayTaxi')->name('everyday.taxi');
        Route::get('airport-transport', 'SettingController@airportTransport')->name('airport.transport');
        Route::get('cruise-transport', 'SettingController@cruiseTransport')->name('cruise.transport');
    });
});

app/Models/Terminal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Terminal extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'address',
        'lat',
        'long',
        'type',
    ];
}

app/Http/Controllers/Admin/TerminalController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Terminal;
use Validator;

class TerminalController extends Controller
{
    public function list()
    {
    	$list = Terminal::all();
    	return view('admin.terminal.list', get_defined_vars());
    }

    public function add()
    {
    	return view('admin.terminal.add');
    }

    public function edit($id = null)
    {
    	$terminal = Terminal::find($id);
    	return view('admin.terminal.edit', get_defined_vars());
    }

    public function save(Request $req, $id = null)
    {
        $message = [
            'name.required' => 'Enter any display name of the location',
            'address.required' => 'Enter address of the terminal',
            'type.required' => 'Select type of terminal',
        ];

        $rules = [
            'name' => 'required',
            'address' => 'required',
            'lat' => 'required',
            'long' => 'required',
            'type' => 'required',
        ];

        $this->validate($req, $rules, $message);

        if (is_null($id)) {
        	$terminal = new Terminal();
        	$terminal->name = $req->name;
        	$terminal->address = $req->address;
        	$terminal->lat = $req->lat;
        	$terminal->long = $req->long;
        	$terminal->type = $req->type;
            $terminal->save();

            $msg = "Terminal Added Successfully!";
        } else {

            $terminal = Terminal::find($id);
        	$terminal->name = $req->name;
        	$terminal->lat = $req->lat;
        	$terminal->long = $req->long;
        	$terminal->type = $req->type;
            $terminal->save();

            $msg = "Terminal Updated Successfully!";
        }

        return redirect()->route('admin.terminal.list')->with('success', $msg);
    }

    public function delete($id = null)
    {
    	Terminal::find($id)->delete();
    	return redirect()->back()->with('success', 'Terminal Deleted Successfully!');
    }

    public function bulkAction(Request $req)
    {
        $ids = explode(",", $req->action_id);
        $action = $req->action;

        foreach ($ids as $id) {
            if ($action === "delete") {
                $this->delete($id);
                $msg = "Bulk Deleted Successfully!";
            }
        }

        return redirect()->back()->with('success', $msg);
    }
}

resources/views/admin/terminal/add.blade.php
@extends('layouts.admin')
@section('title', 'Terminals')
@section('nav-title', 'Terminals')
@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form action="{{ route('admin.terminal.save') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card ">
                    <div class="card-header card-header-rose card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">add</i>
                        </div>
                        <h5 class="card-title">Add Terminal</h5>
                    </div>
                    <div class="card-body ">
                    	<div class="row">
                            <div class="col-12">
                    			<div class="form-group">
                    				<label for="name">Place Name</label>
                    				<input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}" autocomplete="off">
                    				@error('name')
                    					<span class="invalid-feedback">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                    			</div>
                    		</div>
                    		<div class="col-12">
                    			<div class="form-group">
                    				<label for="address">Address</label>
                    				<input type="text" name="address" id="address" class="form-control @error('address') is-invalid @enderror" value="{{ old('address') }}" autocomplete="off">
                    				@error('address')
                    					<span class="invalid-feedback">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                                    <input type="hidden" name="lat" id="lat" value="{{ old('lat') }}">
                                    <input type="hidden" name="long" id="lang" value="{{ old('long') }}">
                    			</div>
                    		</div>
                            <div class="col-12">
                                <div class="form-group">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="radio" name="type" value="1"> Airport Terminal
                                            <span class="circle">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="radio" name="type" value="2"> Cruise Terminal
                                            <span class="circle">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                    @error('type')
                    					<span class="error">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                                </div>
                            </div>
                    	</div>
                    </div>
                    <div class="card-footer mt-4">
                        <button type="submit" class="btn btn-rose">submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA6GhjR-WmiKCgr71McBioeymDd6_Ti_0s&sensor=false&libraries=places"></script>
    <script>
        var address = document.getElementById('address');
        var autocomplete = new google.maps.places.Autocomplete(address,{componentRestrictions:{country:["nl"]}});

        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
            var latitude = place.geometry.location.lat();
            var longitude = place.geometry.location.lng();
            console.log(latitude);
            document.getElementById("lat").value = latitude;
            document.getElementById("lang").value = longitude;
        });
    </script>
@endsection

resources/views/admin/terminal/edit.blade.php
@extends('layouts.admin')
@section('title', 'Categories')
@section('nav-title', 'Categories')
@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form action="{{ route('admin.terminal.save', $terminal->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card ">
                    <div class="card-header card-header-rose card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">edit</i>
                        </div>
                        <h5 class="card-title">Edit Category</h5>
                    </div>
                    <div class="card-body ">
                    	<div class="row">
                            <div class="col-12">
                    			<div class="form-group">
                    				<label for="name">Place Name</label>
                    				<input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $terminal->name) }}" autocomplete="off">
                    				@error('name')
                    					<span class="invalid-feedback">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                    			</div>
                    		</div>
                    		<div class="col-12">
                    			<div class="form-group">
                    				<label for="address">Address</label>
                    				<input type="text" name="address" id="address" class="form-control @error('address') is-invalid @enderror" value="{{ old('address', $terminal->address) }}" autocomplete="off">
                    				@error('address')
                    					<span class="invalid-feedback">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                                    <input type="hidden" name="lat" id="lat" value="{{ old('lat', $terminal->lat) }}">
                                    <input type="hidden" name="long" id="long" value="{{ old('long', $terminal->long) }}">
                    			</div>
                    		</div>
                            <div class="col-12">
                                <div class="form-group">
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="radio" name="type" value="1" {{ $terminal->type == "1" ? 'checked' : '' }}> Airport Terminal
                                            <span class="circle">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="form-check-input" type="radio" name="type" value="2" {{ $terminal->type == "2" ? 'checked' : '' }}> Cruise Terminal
                                            <span class="circle">
                                                <span class="check"></span>
                                            </span>
                                        </label>
                                    </div>
                                    @error('type')
                    					<span class="error">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                                </div>
                            </div>
                    	</div>
                    </div>
                    <div class="card-footer mt-4">
                        <button type="submit" class="btn btn-rose">submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA6GhjR-WmiKCgr71McBioeymDd6_Ti_0s&sensor=false&libraries=places"></script>
    <script>
        var address = document.getElementById('address');
        var autocomplete = new google.maps.places.Autocomplete(address,{componentRestrictions:{country:["nl"]}});

        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
            var latitude = place.geometry.location.lat();
            var longitude = place.geometry.location.lng();
            console.log(latitude);
            document.getElementById("lat").value = latitude;
            document.getElementById("lang").value = longitude;
        });
    </script>
@endsection

resources/views/admin/terminal/list.blade.php
@extends('layouts.admin')
@section('title', 'Terminals')
@section('nav-title', 'Terminals')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon"><i class="material-icons">list</i></div>
                    <h5 class="card-title">Terminals List</h5>
                </div>
                <div class="card-body">
                	<div class="row">
                        <div class="col-md-2 col-sm-3 col-12">
                            <form action="{{ route('admin.terminal.bulk.action') }}" class="bulk-action-form" method="GET">
                                <input type="hidden" name="action_id" id="action_id">
                                <select name="action" id="action" class="form-control">
                                    <option value="0" selected>Bulk Action</option>
                                    <option value="delete">Delete</option>
                                </select>
                            </form>
                        </div>
                        <div class="col-md-10 col-sm-9 col-12">
                            <div class="toolbar text-right">
			                	<a href="{{route('admin.terminal.add')}}" class="btn btn-rose">+ Add Terminal</a>
			                </div>
                        </div>
                	</div>
                	<div class="material-datatables mt-3">
                        <table class="datatables table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Date</th>
                                    <th>Place Name</th>
                                    <th>Address</th>
                                    <th>Type</th>
                                    <th class="text-right">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            	@foreach ($list as $item)
                                <tr>
                                	<td>{{ $item->id }}</td>
                                	<td>{{ $item->created_at->format('d/m/Y') }}</td>
                                	<td>{{ $item->name }}</td>
                                	<td>{{ $item->address }}</td>
                                    <td class="text-center">
                                        @if ($item->type == 1)
                                            Airport Terminal
                                        @else
                                            Cruise Terminal
                                        @endif
                                    </td>
                                	<td class="td-actions text-right">
                                		<a href="{{ route('admin.terminal.edit', $item->id) }}" rel="tooltip" class="btn btn-success btn-round" data-original-title="Edit" title="Edit">
                                            <i class="material-icons">edit</i>
                                        </a>
                                        <button type="button" onclick="deleteAlert('{{ route('admin.terminal.delete', $item->id) }}')" rel="tooltip" class="btn btn-danger btn-round delete-btn" data-original-title="Delete" title="Delete">
                                            <i class="material-icons">delete_outline</i>
                                        </button>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection