routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::get('setlocale/{locale}',function($lang){
    \Session::put('locale', $lang);
    return redirect()->back();
})->name('setlocale');


Route::middleware('language')->group(function () {
    Route::get('/', 'HomeController@home')->name('home');
    Route::get('/private-tours', 'HomeController@privateTours')->name('private.tours');
    Route::get('/everyday-taxi', 'HomeController@everydayTaxi')->name('everyday.taxi');
    Route::get('/airport-transport', 'HomeController@airportTransport')->name('airport.transport');
    Route::get('/cruise-transport', 'HomeController@cruiseTransport')->name('cruise.transport');
    Route::get('/faq', 'HomeController@faq')->name('faq');
    Route::get('/contact', 'HomeController@contact')->name('contact');
    Route::get('/get-a-quote', 'HomeController@getAQuote')->name('get.quote');
    Route::post('/book', 'HomeController@booking')->name('book');
    Route::get('/thankyou', 'HomeController@thankYou')->name('thankyou');
    Route::get('/payment', 'HomeController@payment')->name('payment');
    Route::post('/payment-save', 'HomeController@paymentSave')->name('payment.save');
    Route::post('/contact-save', 'HomeController@contactSave')->name('contact.save');
});


// Admin Unathenticated Routes
Route::get('admin/login', 'Auth\AuthenticatedSessionController@showAdminLoginForm')->name('admin.login');

Route::prefix('admin')->name('admin.')->namespace('Admin')->middleware('auth', 'admin')->group(function() {
    Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
    Route::get('profile', 'DashboardController@profile')->name('profile');
    Route::get('enquiries', 'DashboardController@enquiries')->name('enquiries');
    Route::post('general-update', 'DashboardController@generalUpdate')->name('general.update');
    Route::post('pass-update', 'DashboardController@passUpdate')->name('pass.update');
    Route::get('settings', 'SettingController@settings')->name('setting');
    Route::post('setting-save', 'SettingController@save')->name('setting.save');

    Route::get('transaction', 'DashboardController@transaction')->name('transaction');

    Route::prefix('terminal')->name('terminal.')->group(function() {
    	Route::get('list', 'TerminalController@list')->name('list');
    	Route::get('add', 'TerminalController@add')->name('add');
    	Route::post('save/{id?}', 'TerminalController@save')->name('save');
    	Route::get('edit/{id?}', 'TerminalController@edit')->name('edit');
    	Route::get('delete/{id?}', 'TerminalController@delete')->name('delete');

        Route::get('bulk-action', 'TerminalController@bulkAction')->name('bulk.action');
	});

    Route::prefix('faq')->name('faq.')->group(function() {
    	Route::get('list', 'FaqController@list')->name('list');
    	Route::get('add', 'FaqController@add')->name('add');
    	Route::post('save/{id?}', 'FaqController@save')->name('save');
    	Route::get('edit/{id?}', 'FaqController@edit')->name('edit');
    	Route::get('delete/{id?}', 'FaqController@delete')->name('delete');

    	Route::get('status-change/{id?}', 'FaqController@statusChange')->name('status.change');
        Route::get('bulk-action', 'FaqController@bulkAction')->name('bulk.action');
	});

    Route::prefix('booking')->name('booking.')->group(function() {
    	Route::get('list/{status?}', 'BookingController@list')->name('list');
        Route::get('detail/{id?}', 'BookingController@detail')->name('detail');

        Route::get('status-change/{id?}/{action?}', 'BookingController@statusChange')->name('status.change');
    });

    Route::prefix('cms')->name('cms.')->group(function() {
        Route::get('home-page', 'SettingController@homePage')->name('home.page');
        Route::get('private-tours', 'SettingController@privateTours')->name('private.tours');
        Route::get('everyday-taxi', 'SettingController@everydayTaxi')->name('everyday.taxi');
        Route::get('airport-transport', 'SettingController@airportTransport')->name('airport.transport');
        Route::get('cruise-transport', 'SettingController@cruiseTransport')->name('cruise.transport');
    });
});

app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    use HasFactory;

    protected $fillable = [
        'uuid',
        'from',
        'from_lat',
        'from_long',
        'to',
        'to_lat',
        'to_long',
        'flight_no',
        'arrival_from',
        'airline',
        'meeting_point',
        'ship_name',
        'direction',
        'pickup_datetime',
        'return_datetime',
        'vehicle_type',
        'passenger',
        'large_cases',
        'small_cases',
        'payment_method',
        'phone',
        'name',
        'email',
        'instruction',
        'fare',
        'status',
    ];

    public function transaction() {
        return $this->hasOne("App\Models\Transaction");
    }
}

app/Http/Controllers/Admin/BookingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Jobs\SendQueueEmail;
use Illuminate\Http\Request;
use App\Models\Booking;
use Carbon\Carbon;
use Mail;

class BookingController extends Controller
{
    public function list($status = null)
    {
        if (is_null($status)) {
            $list = Booking::orderBy("id", "DESC")->get();
            return view('admin.booking.list', get_defined_vars());
        } else if ($status == "pending") {
            $list = Booking::where('status', '0')->orderBy("id", "DESC")->get();
            return view('admin.booking.pending', get_defined_vars());
        } else if ($status == "active") {
            $list = Booking::where('status', '1')->orderBy("id", "DESC")->get();
            return view('admin.booking.active', get_defined_vars());
        } else if ($status == "completed") {
            $list = Booking::where('status', '2')->orderBy("id", "DESC")->get();
            return view('admin.booking.completed', get_defined_vars());
        } else if ($status == "cancelled") {
            $list = Booking::where('status', '3')->orderBy("id", "DESC")->get();
            return view('admin.booking.cancelled', get_defined_vars());
        }
    }

    public function detail($id = null)
    {
        $booking = Booking::find($id);

        return view('admin.booking.detail', get_defined_vars());
    }

    public function statusChange($id = null, $action = null)
    {
        $book = Booking::find($id);

        if ($action == "accept") {
            $book->status = "1";
            $book->save();

            $details = [
                'id' => $book->id,
                'action' => 'accept',
            ];

            // $job = (new SendQueueEmail($details))->delay(now()->addSeconds(2));

            // dispatch($job);
            
            Mail::send('email.booking_accept', get_defined_vars(), function ($message) use($book) {
                $message->to($book->email, $book->name);
                $message->subject('Booking ID: '.$book->uuid.' booking accepted');
            });
            Mail::send('email.admin.booking_accept', get_defined_vars(), function ($message) use($book) {
                $message->to(adminEmail(), adminName());
                $message->subject('Booking ID: '.$book->uuid.' booking accepted');
            });
        }

        if ($action == "complete") {
            $book->status = "2";
            $book->save();

            $details = [
                'id' => $book->id,
                'action' => 'complete',
            ];

            // $job = (new SendQueueEmail($details))->delay(now()->addSeconds(2));

            // dispatch($job);
            
            Mail::send('email.booking_complete', get_defined_vars(), function ($message) use($book) {
                $message->to($book->email, $book->name);
                $message->subject('Booking ID: '.$book->uuid.' booking completed');
            });
            Mail::send('email.admin.booking_complete', get_defined_vars(), function ($message) use($book) {
                $message->to(adminEmail(), adminName());
                $message->subject('Booking ID: '.$book->uuid.' booking completed');
            });
        }

        if ($action == "decline") {
            $book->status = "3";
            $book->save();

            if ($book->payment_method == "3") {
                $trans = $book->transaction;

                try {
                    \Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));
                    $refund = \Stripe\Refund::create(['charge' => $trans->stripe_charge_id]);

                    $trans->status = "2";
                    $trans->save();

                } catch(\Stripe\Error\InvalidRequest $e) {
                    dd($e->getMessage());
                } catch(\Stripe\Error\Card $e) {
                    dd($e->getMessage());
                }
            }

            $details = [
                'id' => $book->id,
                'action' => 'decline',
            ];

            // $job = (new SendQueueEmail($details))->delay(now()->addSeconds(2));

            // dispatch($job);
            
            Mail::send('email.booking_cancel', get_defined_vars(), function ($message) use($book) {
                $message->to($book->email, $book->name);
                $message->subject('Booking ID: '.$book->uuid.' booking cancelled');
            });
            Mail::send('email.admin.booking_cancel', get_defined_vars(), function ($message) use($book) {
                $message->to(adminEmail(), adminName());
                $message->subject('Booking ID: '.$book->uuid.' booking cancelled');
            });
        }

        return redirect()->back()->with('success', 'Booking Status Changed Successfully!');
    }
}

resources/views/admin/booking/active.blade.php
@extends('layouts.admin')
@section('title', 'Bookings')
@section('nav-title', 'Bookings')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 m-auto">
            <div class="page-categories">
                <ul class="nav nav-pills nav-pills-rose nav-pills-icons justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.booking.list') }}">
                            <i class="material-icons">border_all</i> All
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.booking.list', 'pending') }}">
                            <i class="material-icons">pending</i> Pending
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ route('admin.booking.list', 'active') }}">
                            <i class="material-icons">toc</i> Active
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.booking.list', 'completed') }}">
                            <i class="material-icons">done_outline</i> Completed
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.booking.list', 'cancelled') }}">
                            <i class="material-icons">hide_source</i> Cancelled
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon"><i class="material-icons">list</i></div>
                    <h5 class="card-title">Bookings List</h5>
                </div>
                <div class="card-body">
                	<div class="material-datatables mt-3">
                        <table class="datatables table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Date</th>
                                    <th>From</th>
                                    <th>To</th>
                                    <th>Fare</th>
                                    <th>Status</th>
                                    <th class="text-right">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            	@foreach ($list as $item)
                                <tr>
                                	<td>{{ $item->id }}</td>
                                	<td>{{ $item->created_at->format('d/m/Y') }}</td>
                                	<td>{{ $item->from }}</td>
                                	<td>{{ $item->to }}</td>
                                    <td>£{{ $item->fare }}</td>
                                    <td class="text-center">
                                        @if ($item->status == "0")
                                            <span class="badge badge-warning">Pending</span>
                                        @elseif($item->status == "1")
                                            <span class="badge badge-success">Accepted</span>
                                        @elseif($item->status == "2")
                                            <span class="badge badge-rose">Completed</span>
                                        @else
                                            <span class="badge badge-danger">Cancelled</span>
                                        @endif
                                    </td>
                                	<td class="td-actions text-right">
                                		<a href="{{ route('admin.booking.detail', $item->id) }}" rel="tooltip" class="btn btn-rose btn-round" data-original-title="View Details" title="View Details">
                                            <i class="material-icons">remove_red_eye</i>
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/booking/cancelled.blade.php
@extends('layouts.admin')
@section('title', 'Bookings')
@section('nav-title', 'Bookings')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 m-auto">
            <div class="page-categories">
                <ul class="nav nav-pills nav-pills-rose nav-pills-icons justify-content-center">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.booking.list') }}">
                            <i class="material-icons">border_all</i> All
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.booking.list', 'pending') }}">
                            <i class="material-icons">pending</i> Pending
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.booking.list', 'active') }}">
                            <i class="material-icons">toc</i> Active
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.booking.list', 'completed') }}">
                            <i class="material-icons">done_outline</i> Completed
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ route('admin.booking.list', 'cancelled') }}">
                            <i class="material-icons">hide_source</i> Cancelled
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon"><i class="material-icons">list</i></div>
                    <h5 class="card-title">Bookings List</h5>
                </div>
                <div class="card-body">
                	<div class="material-datatables mt-3">
                        <table class="datatables table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Date</th>
                                    <th>From</th>
                                    <th>To</th>
                                    <th>Fare</th>
                                    <th>Status</th>
                                    <th class="text-right">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            	@foreach ($list as $item)
                                <tr>
                                	<td>{{ $item->id }}</td>
                                	<td>{{ $item->created_at->format('d/m/Y') }}</td>
                                	<td>{{ $item->from }}</td>
                                	<td>{{ $item->to }}</td>
                                    <td>£{{ $item->fare }}</td>
                                    <td class="text-center">
                                        @if ($item->status == "0")
                                            <span class="badge badge-warning">Pending</span>
                                        @elseif($item->status == "1")
                                            <span class="badge badge-success">Accepted</span>
                                        @elseif($item->status == "2")
                                            <span class="badge badge-rose">Completed</span>
                                        @else
                                            <span class="badge badge-danger">Cancelled</span>
                                        @endif
                                    </td>
                                	<td class="td-actions text-right">
                                		<a href="{{ route('admin.booking.detail', $item->id) }}" rel="tooltip" class="btn btn-rose btn-round" data-original-title="View Details" title="View Details">
                                            <i class="material-icons">remove_red_eye</i>
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/booking/detail.blade.php
@extends('layouts.admin')
@section('title', 'Bookings')
@section('nav-title', 'Bookings')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon"><i class="material-icons">toc</i></div>
                    <h5 class="card-title">Booking ID: {{ $booking->uuid }}</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">From:</h5>
                            <p>{{ $booking->from }}</p>
                        </div>

                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">To:</h5>
                            <p>{{ $booking->to }}</p>
                        </div>

                        @if (!is_null($booking->flight_no))
                            <div class="col-md-6 mb-2">
                                <h5 class="font-weight-bold mb-0">Flight Number    :</h5>
                                <p>{{ $booking->flight_no }}</p>
                            </div>
                        @endif

                        @if (!is_null($booking->arrival_from))
                            <div class="col-md-6 mb-2">
                                <h5 class="font-weight-bold mb-0">Arrival From    :</h5>
                                <p>{{ $booking->arrival_from }}</p>
                            </div>
                        @endif

                        @if (!is_null($booking->airline))
                            <div class="col-md-6 mb-2">
                                <h5 class="font-weight-bold mb-0">Airline    :</h5>
                                <p>{{ $booking->airline }}</p>
                            </div>
                        @endif

                        @if (!is_null($booking->meeting_point))
                            <div class="col-md-6 mb-2">
                                <h5 class="font-weight-bold mb-0">Booking Point    :</h5>
                                <p>{{ $booking->meeting_point }}</p>
                            </div>
                        @endif

                        @if (!is_null($booking->ship_name))
                            <div class="col-md-6 mb-2">
                                <h5 class="font-weight-bold mb-0">Ship Name    :</h5>
                                <p>{{ $booking->ship_name }}</p>
                            </div>
                        @endif

                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Direction:</h5>
                            <p>
                                @if ($booking->direction == "1")
                                    One Way
                                @else
                                    Two Way
                                @endif
                            </p>
                        </div>

                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Pickup Date Time:</h5>
                            <p>{{ $booking->pickup_datetime }}</p>
                        </div>

                        @if (!is_null($booking->return_datetime))
                            <div class="col-md-6 mb-2">
                                <h5 class="font-weight-bold mb-0">Return Date Time:</h5>
                                <p>{{ $booking->return_datetime }}</p>
                            </div>
                        @endif

                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Passengers:</h5>
                            <p>{{ $booking->passenger }}</p>
                        </div>
                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Large Cases:</h5>
                            <p>{{ $booking->large_cases }}</p>
                        </div>
                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Small Cases:</h5>
                            <p>{{ $booking->small_cases }}</p>
                        </div>

                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Payment Method:</h5>
                            <p>
                                @if ($booking->payment_method == "1")
                                    Cash in Car
                                @elseif ($booking->payment_method == "2")
                                    Card in Car
                                @else
                                    Paid via stripe <a href="{{ route('admin.transaction') }}/?booking_id={{ $booking->id }}">View Transaction</a>
                                @endif
                            </p>
                        </div>

                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Phone:</h5>
                            <p>{{ $booking->phone }}</p>
                        </div>
                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Name:</h5>
                            <p>{{ $booking->name }}</p>
                        </div>
                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Email:</h5>
                            <p>{{ $booking->email }}</p>
                        </div>

                        @if (!is_null($booking->instruction))
                            <div class="col-md-12 mb-2">
                                <h5 class="font-weight-bold mb-0">Instruction:</h5>
                                <p>{{ $booking->instruction }}</p>
                            </div>
                        @endif

                        <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Estimated Fare:</h5>
                            <h3 class="font-weight-bold m-0">€ {{ $booking->fare }}</h3>
                        </div>
                        {{-- <div class="col-md-6 mb-2">
                            <h5 class="font-weight-bold mb-0">Status:</h5>
                            <p>
                                @if ($booking->status == "0")
                                    <span class="badge badge-warning">Pending</span>
                                @elseif ($booking->status == "1")
                                    <span class="badge badge-success">Accepted</span>
                                @elseif ($booking->status == "2")
                                    <span class="badge badge-rose">Completed</span>
                                @else
                                    <span class="badge badge-danger">Cancelled</span>
                                @endif
                            </p>
                        </div> --}}

                        {{-- <div class="col-12 text-center justify-content-center">
                            @if ($booking->status != "3")
                                @if ($booking->status == "1")
                                    <a href="{{ route('admin.booking.status.change', [$booking->id, 'complete']) }}" class="btn btn-success">Mark as Complete</a>
                                @else
                                    <a href="{{ route('admin.booking.status.change', [$booking->id, 'accept']) }}" class="btn btn-rose">Accept</a>
                                    <a href="{{ route('admin.booking.status.change', [$booking->id, 'decline']) }}" class="btn btn-danger">Decline</a>
                                @endif
                            @endif
                        </div> --}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection