routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::get('setlocale/{locale}',function($lang){
    \Session::put('locale', $lang);
    return redirect()->back();
})->name('setlocale');


Route::middleware('language')->group(function () {
    Route::get('/', 'HomeController@home')->name('home');
    Route::get('/private-tours', 'HomeController@privateTours')->name('private.tours');
    Route::get('/everyday-taxi', 'HomeController@everydayTaxi')->name('everyday.taxi');
    Route::get('/airport-transport', 'HomeController@airportTransport')->name('airport.transport');
    Route::get('/cruise-transport', 'HomeController@cruiseTransport')->name('cruise.transport');
    Route::get('/faq', 'HomeController@faq')->name('faq');
    Route::get('/contact', 'HomeController@contact')->name('contact');
    Route::get('/get-a-quote', 'HomeController@getAQuote')->name('get.quote');
    Route::post('/book', 'HomeController@booking')->name('book');
    Route::get('/thankyou', 'HomeController@thankYou')->name('thankyou');
    Route::get('/payment', 'HomeController@payment')->name('payment');
    Route::post('/payment-save', 'HomeController@paymentSave')->name('payment.save');
    Route::post('/contact-save', 'HomeController@contactSave')->name('contact.save');
});


// Admin Unathenticated Routes
Route::get('admin/login', 'Auth\AuthenticatedSessionController@showAdminLoginForm')->name('admin.login');

Route::prefix('admin')->name('admin.')->namespace('Admin')->middleware('auth', 'admin')->group(function() {
    Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
    Route::get('profile', 'DashboardController@profile')->name('profile');
    Route::get('enquiries', 'DashboardController@enquiries')->name('enquiries');
    Route::post('general-update', 'DashboardController@generalUpdate')->name('general.update');
    Route::post('pass-update', 'DashboardController@passUpdate')->name('pass.update');
    Route::get('settings', 'SettingController@settings')->name('setting');
    Route::post('setting-save', 'SettingController@save')->name('setting.save');

    Route::get('transaction', 'DashboardController@transaction')->name('transaction');

    Route::prefix('terminal')->name('terminal.')->group(function() {
    	Route::get('list', 'TerminalController@list')->name('list');
    	Route::get('add', 'TerminalController@add')->name('add');
    	Route::post('save/{id?}', 'TerminalController@save')->name('save');
    	Route::get('edit/{id?}', 'TerminalController@edit')->name('edit');
    	Route::get('delete/{id?}', 'TerminalController@delete')->name('delete');

        Route::get('bulk-action', 'TerminalController@bulkAction')->name('bulk.action');
	});

    Route::prefix('faq')->name('faq.')->group(function() {
    	Route::get('list', 'FaqController@list')->name('list');
    	Route::get('add', 'FaqController@add')->name('add');
    	Route::post('save/{id?}', 'FaqController@save')->name('save');
    	Route::get('edit/{id?}', 'FaqController@edit')->name('edit');
    	Route::get('delete/{id?}', 'FaqController@delete')->name('delete');

    	Route::get('status-change/{id?}', 'FaqController@statusChange')->name('status.change');
        Route::get('bulk-action', 'FaqController@bulkAction')->name('bulk.action');
	});

    Route::prefix('booking')->name('booking.')->group(function() {
    	Route::get('list/{status?}', 'BookingController@list')->name('list');
        Route::get('detail/{id?}', 'BookingController@detail')->name('detail');

        Route::get('status-change/{id?}/{action?}', 'BookingController@statusChange')->name('status.change');
    });

    Route::prefix('cms')->name('cms.')->group(function() {
        Route::get('home-page', 'SettingController@homePage')->name('home.page');
        Route::get('private-tours', 'SettingController@privateTours')->name('private.tours');
        Route::get('everyday-taxi', 'SettingController@everydayTaxi')->name('everyday.taxi');
        Route::get('airport-transport', 'SettingController@airportTransport')->name('airport.transport');
        Route::get('cruise-transport', 'SettingController@cruiseTransport')->name('cruise.transport');
    });
});

app/Models/Faq.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    use HasFactory;

    protected $fillable = [
        'question',
        'answer',
        'status',
    ];
}

app/Http/Controllers/Admin/FaqController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Faq;

class FaqController extends Controller
{
    public function list()
    {
    	$list = Faq::all();
    	return view('admin.faq.list', get_defined_vars());
    }

    public function add()
    {
    	return view('admin.faq.add');
    }

    public function edit($id = null)
    {
    	$faq = Faq::find($id);
    	return view('admin.faq.edit', get_defined_vars());
    }

    public function save(Request $req, $id = null)
    {
        $message = [
            'question.required' => 'Please fill out this!',
            'answer.required' => 'Please fill out this!',
        ];

        $rules = [
            'question' => 'required',
            'answer' => 'required',
        ];

        $this->validate($req, $rules, $message);

        if (is_null($id)) {
        	$faq = new Faq();
        	$faq->question = $req->question;
        	$faq->answer = $req->answer;
            $faq->save();

            $msg = "Faq Added Successfully!";
        } else {

            $faq = Faq::find($id);
        	$faq->question = $req->question;
        	$faq->answer = $req->answer;
            $terminal->save();

            $msg = "Faq Updated Successfully!";
        }

        return redirect()->route('admin.faq.list')->with('success', $msg);
    }

    public function delete($id = null)
    {
    	Faq::find($id)->delete();
    	return redirect()->back()->with('success', 'Faq Deleted Successfully!');
    }

    public function statusChange($id = null)
    {
        $faq = Faq::find($id);

        if ($faq->status == 1) {
            $faq->status = 0;
        } else {
            $faq->status = 1;
        }
        $faq->save();

        return redirect()->back()->with('success', 'Faq Status Change Successfully!');
    }

    public function bulkAction(Request $req)
    {
        $ids = explode(",", $req->action_id);
        $action = $req->action;

        foreach ($ids as $id) {
            if ($action === "delete") {
                $this->delete($id);
                $msg = "Bulk Deleted Successfully!";
            }

            if ($action === "hide") {
                $this->statusChange($id);
                $msg = "Bulk Status Change Successfully!";
            }

            if ($action === "show") {
                $this->statusChange($id);
                $msg = "Bulk Status Change Successfully!";
            }
        }

        return redirect()->back()->with('success', $msg);
    }
}

resources/views/admin/faq/add.blade.php
@extends('layouts.admin')
@section('title', 'FAQs')
@section('nav-title', 'FAQs')
@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form action="{{ route('admin.faq.save') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card ">
                    <div class="card-header card-header-rose card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">add</i>
                        </div>
                        <h5 class="card-title">Add Faq</h5>
                    </div>
                    <div class="card-body ">
                    	<div class="row">
                            <div class="col-12">
                    			<div class="form-group">
                    				<label for="name">Question</label>
                    				<input type="text" name="question" id="question" class="form-control @error('question') is-invalid @enderror" value="{{ old('question') }}" autocomplete="off">
                    				@error('question')
                    					<span class="invalid-feedback">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                    			</div>
                    		</div>
                    		<div class="col-12">
                    			<div class="form-group">
                    				<label for="answer">Address</label>
                    				<textarea name="answer" id="answer" class="answer" rows="10"></textarea>
                    				@error('address')
                    					<span class="invalid-feedback">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                    			</div>
                    		</div>
                    	</div>
                    </div>
                    <div class="card-footer mt-4">
                        <button type="submit" class="btn btn-rose">submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script>
        CKEDITOR.replace( 'answer' );
    </script>
@endsection

resources/views/admin/faq/edit.blade.php
@extends('layouts.admin')
@section('title', 'FAQs')
@section('nav-title', 'FAQs')
@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form action="{{ route('admin.faq.save', $faq->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card ">
                    <div class="card-header card-header-rose card-header-icon">
                        <div class="card-icon">
                            <i class="material-icons">add</i>
                        </div>
                        <h5 class="card-title">Add Faq</h5>
                    </div>
                    <div class="card-body ">
                    	<div class="row">
                            <div class="col-12">
                    			<div class="form-group">
                    				<label for="name">Question</label>
                    				<input type="text" name="question" id="question" class="form-control @error('question') is-invalid @enderror" value="{{ old('question', $faq->question) }}" autocomplete="off">
                    				@error('question')
                    					<span class="invalid-feedback">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                    			</div>
                    		</div>
                    		<div class="col-12">
                    			<div class="form-group">
                    				<label for="answer">Address</label>
                    				<textarea name="answer" id="answer" class="answer" rows="10">{{ $faq->answer }}</textarea>
                    				@error('address')
                    					<span class="invalid-feedback">
                    						<strong>{{ $message }}</strong>
                    					</span>
                    				@enderror
                    			</div>
                    		</div>
                    	</div>
                    </div>
                    <div class="card-footer mt-4">
                        <button type="submit" class="btn btn-rose">submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script>
        CKEDITOR.replace( 'answer' );
    </script>
@endsection

resources/views/admin/faq/list.blade.php
@extends('layouts.admin')
@section('title', 'FAQs')
@section('nav-title', 'FAQs')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon"><i class="material-icons">list</i></div>
                    <h5 class="card-title">FAQs List</h5>
                </div>
                <div class="card-body">
                	<div class="row">
                        <div class="col-md-2 col-sm-3 col-12">
                            <form action="{{ route('admin.faq.bulk.action') }}" class="bulk-action-form" method="GET">
                                <input type="hidden" name="action_id" id="action_id">
                                <select name="action" id="action" class="form-control">
                                    <option value="0" selected>Bulk Action</option>
                                    <option value="delete">Delete</option>
                                    <option value="hide">Hide</option>
                                    <option value="show">Show</option>
                                </select>
                            </form>
                        </div>
                        <div class="col-md-10 col-sm-9 col-12">
                            <div class="toolbar text-right">
			                	<a href="{{route('admin.faq.add')}}" class="btn btn-rose">+ Add Faq</a>
			                </div>
                        </div>
                	</div>
                	<div class="material-datatables mt-3">
                        <table class="datatables table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Date</th>
                                    <th>Question</th>
                                    <th>Status (Click to change)</th>
                                    <th class="text-right">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            	@foreach ($list as $item)
                                <tr>
                                	<td>{{ $item->id }}</td>
                                	<td>{{ $item->created_at->format('d/m/Y') }}</td>
                                	<td>{{ $item->question }}</td>
                                    <td class="text-center">
                                        @if ($item->status == 1)
                                            <a href="{{ route('admin.faq.status.change') }}"><span class="badge badge-success">Hide</span></a>
                                        @else
                                            <a href="{{ route('admin.faq.status.change') }}"><span class="badge badge-danger">Show</span></a>
                                        @endif
                                    </td>
                                	<td class="td-actions text-right">
                                		<a href="{{ route('admin.faq.edit', $item->id) }}" rel="tooltip" class="btn btn-success btn-round" data-original-title="Edit" title="Edit">
                                            <i class="material-icons">edit</i>
                                        </a>
                                        <button type="button" onclick="deleteAlert('{{ route('admin.faq.delete', $item->id) }}')" rel="tooltip" class="btn btn-danger btn-round delete-btn" data-original-title="Delete" title="Delete">
                                            <i class="material-icons">delete_outline</i>
                                        </button>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection